version: "3.9"

services:
  web:
    build:
      context: ./project
      dockerfile: ./Dockerfile
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/project/web/static
      - media_volume:/home/project/web/media
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env.prod

  db:
    image: postgres:14.6-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/project/web/static
      - media_volume:/home/project/web/media
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  db_data:
  static_volume:
  media_volume: